name = "io-theme"
description = "A fork of Beautiful Hugo theme"

[author]
    name = "moosebot"
    homepage = "http://valle.io"

# If Porting existing theme
[original]
    author =  "halogenica"
    homepage = "http://halogenica.net"
    repo = "https://github.com/halogenica/beautifulhugo"
