baseURL = 'http://valle.io/'
languageCode = 'en-us'
title = 'valle.io'
theme = 'io-theme'
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  homeTitle = 'Beautiful Hugo Theme'
  subtitle = 'Software!'
  logo = 'https://avatars1.githubusercontent.com/u/8650838?s=460&v=4'#'img/avatar-icon.png'
  favicon = 'img/favicon.ico'
  dateFormat = 'Jan 2, 2006'
  commit = false
  rss = true
  comments = true
  #readingTime = true
  useHLJS = false
  socialShare = true

[Author]
  name = 'Austin Valle'
  website = 'valle.io'
  email = 'austinvalle@gmail.com'
  github = 'moosebot'
  twitter = '_moosebot'
  linkedin = 'austin-valle-9773496a'
  youtube = 'user/OhMyG0OdNess'

[[menu.main]]
    name = 'About'
    url = 'about/'
    weight = 1

[[menu.main]]
    name = 'Blog'
    url = 'posts/'
    weight = 2