baseurl = "https://valle.io"
title = "valle.io"
theme = "valle.io"

[Params]

[Author]
  name = "Austin Valle"
  email = "austinvalle@gmail.com"
  github = "moosebot"
  twitter = "_moosebot"
  linkedin = "austin-valle-9773496a"
  stackoverflow = "users/6777540/austin-valle"
  youtube = "channel/UC6G4-Xp-d-geuCGoITlCwZw"
