name = "valle.Io"
license = "MIT"
licenselink = "https://github.com/moosebot/valle.io/blob/master/themes/valle.io/LICENSE"
description = ""
homepage = "https://github.com/moosebot/valle.io/tree/master/themes/valle.io"
tags = []
features = []
min_version = "0.41"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
